app = "okx-yfhkuq"
primary_region = "iad"

[build]

[env]
  FLASK_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[processes]
  app = "python main.py"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
